---
title: "2020FA MATH 1051H: Lecture Links"
author: 'Dr. Wesley S. Burr'
date: 2020-10-22
output:
  xaringan::moon_reader:
    chakra: remark-latest.min.js
    lib_dir: libs
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      highlightLanguage: r
    includes:
      in_header: header.html
    countIncrementalSlides: false
    css: example.css
---

class: inverse

```{r include=FALSE}
library(ggplot2)
filter <- dplyr::filter
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.width=10.5, fig.height=4, 
  comment=NA, rows.print=16)
theme_set(theme_gray(base_size = 24))
```

## Lecture Slide Links

The following slides have links to the lecture slides for the 2020FA semester offering of
MATH 1051H at Trent University. 

<br />

* the HTML slides are the canonical format
* the PDFs will be used for markup purposes on tablets

---

class: inverse

## Week 01

<a href="./Week01/week01.html">HTML</a>; 
<a href="./Week01/week01.pdf">PDF</a>

<br/>

**Lecture 01 - Introduction**

<a href="./Lecture01/lecture01.html">HTML</a>; 
<a href="./Lecture01/lecture01.pdf">PDF</a>

<br />

**Lecture 02 - Chapter 1**

<a href="./Lecture02/lecture02.html">HTML</a>; 
<a href="./Lecture02/lecture02.pdf">PDF</a>

<br />


**Lecture 02b - Chapter 1**

<a href="./Lecture02b/lecture02b.html">HTML</a>; 
<a href="./Lecture02b/lecture02b.pdf">PDF</a>

<br />

---

class: inverse

## Week 02

<a href="./Week02/week02.html">HTML</a>; 
<a href="./Week02/week02.pdf">PDF</a>

<br/>

**Lecture 03 - Experiments versus Observational**

<a href="./Lecture03/lecture03.html">HTML</a>; 
<a href="./Lecture03/lecture03.pdf">PDF</a>

<br />

**Lecture 04 - Summarizing Data**

<a href="./Lecture04/lecture04.html">HTML</a>; 
<a href="./Lecture04/lecture04.pdf">PDF</a>

<br />


---

class: inverse

## Week 03

<a href="./Week03/week03.html">HTML</a>; 
<a href="./Week03/week03.pdf">PDF</a>

<br/>

**Lecture 05 - Examples of Summaries**

<a href="./Lecture05/lecture05.html">HTML</a>; 
<a href="./Lecture05/lecture05.pdf">PDF</a>

<br />

**Lecture 06 - Introduction to Probability**

<a href="./Lecture06/lecture06.html">HTML</a>; 
<a href="./Lecture06/lecture06.pdf">PDF</a>

<br />


---

class: inverse

## Week 04

<a href="./Week04/week04.html">HTML</a>; 
<a href="./Week04/week04.pdf">PDF</a>

<br/>

**Lecture 07 - Random Variables**

<a href="./Lecture07/lecture07.html">HTML</a>; 
<a href="./Lecture07/lecture07.pdf">PDF</a>

<br />

**Lecture 08 - Binomial and Normal Distributions**

<a href="./Lecture08/lecture08.html">HTML (live)</a>; 
<a href="./Lecture08/lecture08_live.pdf">PDF (live)</a>;
<a href="./Lecture08/lecture08_asynch.pdf">PDF (asynch)</a>
<br />


---

class: inverse

## Week 05

<a href="./Week05/week05.html">HTML</a>; 
<a href="./Week05/week05.pdf">PDF</a>

<br/>

**Lecture 09 - Normal Approx to Binomial; Inverse Normal**

<a href="./Lecture09/lecture09.html">HTML</a>; 
<a href="./Lecture09/lecture09.pdf">PDF</a>

<br />

**Lecture 10 - Binomial + Normal, Problem Solving**

<a href="./Lecture10/lecture10.html">HTML (live)</a>; 
<a href="./Lecture10/lecture10_asynch.pdf">PDF (asynch)</a>
<br />

---

class: inverse

## Week 06

<a href="./Week06/week06.html">HTML</a>; 
<a href="./Week06/week06.pdf">PDF</a>

<br/>

**Lecture 11 - Canceled**

<br />

**Lecture 12 - Scatterplots and Linear Models**

<a href="./Lecture12/lecture12.html">HTML (live)</a>; 
<a href="./Lecture12/lecture12_asynch.pdf">PDF (asynch)</a>
<br />

---

class: inverse

## Week 07

<a href="./Week07/week07.html">HTML</a>; 
<a href="./Week07/week07.pdf">PDF</a>

<br/>

**Lecture 13 - Sampling Distributions and the CLT**

<a href="./Lecture13/lecture13.html">HTML (asynch)</a>; 
<a href="./Lecture13/lecture13.pdf">PDF (asynch)</a>
<br />

**Lecture 14 - Hypothesis Tests**

<a href="./Lecture14/lecture14.html">HTML (asynch)</a>; 
<a href="./Lecture14/lecture14.pdf">PDF (asynch)</a>
<br />

---

class: inverse

## Week 08

<a href="./Week07/week07.html">HTML</a>; 
<a href="./Week07/week07.pdf">PDF</a>

<br/>

**Lecture 15 - t distribution, Linear Model Hypotheses**

<a href="./Lecture15/lecture15.html">HTML (asynch)</a>; 
<a href="./Lecture15/lecture15.pdf">PDF (asynch)</a>
<br />

**Lecture 16 - More Hypothesis Tests**

<a href="./Lecture16/lecture16.html">HTML (asynch)</a>; 
<a href="./Lecture16/lecture16.pdf">PDF (asynch)</a>
<br />

